update the yarn auto version script

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -36,16 +36,21 @@ jobs:
 
       - name: Apply semver updates (if any)
         run: |
-          if yarn auto version; then
-            AUTO_VERSION=$(yarn auto version)
-            echo "Auto Version: $AUTO_VERSION"
-            if [[ $AUTO_VERSION == pre* ]]; then
-              yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes --preid "$GITHUB_REF"
-            elif [[ $AUTO_VERSION ]]; then
-              yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes
-            fi
+          AUTO_VERSION=$(yarn auto version)
+
+          EXIT_CODE=$?
+
+          if [[ $EXIT_CODE -ne 0 || -z "$AUTO_VERSION" ]]; then
+            echo "Unable to bump version successfully."
+            exit 1
+          fi
+
+          echo "Auto Version: $AUTO_VERSION"
+
+          if [[ $AUTO_VERSION == pre* ]]; then
+            yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes --preid "$GITHUB_REF"
           else
-            echo "Unable to bump version successfully." && exit 1
+            yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes
           fi
 
       - name: Build
